# This options block is required for builds that use a custom service account.
options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET

steps:
# Step 1: Build the container image.
# The image is tagged with the unique Git commit SHA (${SHORT_SHA}).
- name: 'gcr.io/cloud-builders/docker'
  id: Build
  args: ['build', '-t', 'us-central1-docker.pkg.dev/my-gcp-proj-408007/autopilot-repo/hello-world-app:${SHORT_SHA}', 'app']
# Step 2: Push the unique image to Artifact Registry.
- name: 'gcr.io/cloud-builders/docker'
  id: Push
  args: ['push', 'us-central1-docker.pkg.dev/my-gcp-proj-408007/autopilot-repo/hello-world-app:${SHORT_SHA}']
# Step 3: Replace the image placeholder in the manifest.
# The 'sed' command ensures the deployment manifest points to the new image.
- name: 'gcr.io/cloud-builders/gke-deploy'
  id: Replace Image
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    sed -i "s|REPLACE_IMAGE|us-central1-docker.pkg.dev/my-gcp-proj-408007/autopilot-repo/hello-world-app:${SHORT_SHA}|g" k8s/deployment.yaml
# Step 4: Deploy to GKE.
# Because the manifest is now updated, this command triggers a rolling update
# that replaces the old pods with new ones running the latest image.
- name: 'gcr.io/cloud-builders/gke-deploy'
  id: Deploy
  args:
  - 'run'
  - '--filename=k8s/deployment.yaml'
  - '--location=us-central1'
  - '--cluster=autopilot-cicd-cluster'
  - '--namespace=default'
  - '--app=hello-world-app'
